name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: "3.108.140.82"
          username: "ec2-user"
          key: ${{ secrets.KEY }}
          script: |
            mkdir -p ~/be-Assigmnert-App
            cd ~/be-Assigmnert-App
            git init
            git remote add origin git@github.com:AK7745/be-Assigmnert-App.git
            git fetch origin main
            git reset --hard origin/main
            npm ci
            pm2 start index.js
            pm2 save
      

      - name: Restart Nginx
        run: sudo systemctl restart nginx
