name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: "3.108.140.82"
          username: "ec2-user"
          key: ${{ secrets.KEY }}
          script: |
            mkdir be-Assigmnert-App
            cd ~/home/ec2-user/be-Assigmnert-App
            git clone git@github.com:AK7745/be-Assigmnert-App.git .
            git pull origin master
            git status
            npm i
            pm2 -f start index.js


      # - name: Deploy to EC2
      #   run: |
      #     ssh-keyscan -H 3.108.140.82 >> $HOME/.ssh/known_hosts
      #     ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-108-140-82.ap-south-1.compute.amazonaws.com 'cd /home/ec2-user/be-Assigmnert-App && npm ci && pm2 restart index.js'

      - name: Restart Nginx
        run: sudo systemctl restart nginx
