name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH private key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        run: |
          ssh-keyscan -H 3.108.140.82 >> $HOME/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-108-140-82.ap-south-1.compute.amazonaws.com 
          cd /home/ec2-user/be-Assigmnert-App/
          npm i 
          pm2 restart index.js
          sudo systemctl restart nginx
